iac_certificates:
- host: avr.politie.local
iac_crontabentries:
- name: "houdt storage groei bij"
  admin_only: "true"
  minute: "0"
  hour: "6"
  weekday: "1"
  job: '(date +"%d-%m-%Y %T" && df -P /mnt/*) >> /var/log/wls/MS-AVR-*/storage_usage.log'
- name: "alert als meer dan 80%"
  admin_only: "true"
  minute: "0" 
  hour: "7"
  job: 'df -hP /mnt/avr* | grep [89].%  ; [ $? == 1 ]; (df -hP /mnt/avr*) | mail -s "{{ CODE }} `hostname -f` meer dan 80% vol" "{{ alertemailaddress }}" '
  # alertemailaddress: "peter.de.zwart@politie.nl"
